<TopBar>:
    size_hint_y: None
    size_y: 100
    canvas:
        Color:
            rgba: (0, 1, 1, 1)
        Rectangle:
            size: self.size
            pos: self.pos
    ActionBar:
        ActionPrevious:
        ActionView:
            ActionButton:
                text: "Button 1"
                on_release: app.button1()
<PictureBox>:
    canvas.before:
        Color:
            rgba: (0, 1, 0, 1)
        Rectangle:
            size: self.size
            pos: self.pos

<SeriesBox>:
    size_hint_y: 0.25
    canvas:
        Color:
            rgba: (0, 0, 1, 1)
        Rectangle:
            size: self.size
            pos: self.pos

<Parameters>:
    size_hint: 1, 1
    canvas:
        Color:
            rgba: (0, 1, 1, 1)
        Rectangle:
            size: self.size
            pos: self.pos
    Slider:
    Slider:
        

<TrainingLayout>:
    orientation: 'vertical'
    TopBar:
        Label:
        Button:
            text: 'START'
            width: self.height
            size_hint_x: None
            on_release: self.parent.show_menu()

    PictureBox:
        id:pictureBox
        Image:
            id:stretchImage
            source: self.source

    SeriesBox:
        Button:
            text: 'START'
            width: self.height
            size_hint_x: None
            on_press: root.start_stretching()